### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'userAgent' of undefined

### ISSUE THREAD

**Issue by GenieTim** [Niek/playwright-addons#8]
Thanks for these awesome addons, very helpful.

When using the addons like this:

```
const browserType = await playwright['firefox']
browser = await browserType.launch({
        headless: !this.debug
      })
context = await browser.newContext()
      // block possible tracking scripts to reduce overhead
      const addons = await import('playwright-addons');
      await addons.adblocker(browser)
      await addons.stealth(browser)
```

I get the following warning of an error:

```
(node:22972) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'userAgent' of undefined
   at file:///home/.../yarn/global/node_modules/playwright-addons/stealth/index.js:23:42
   at runNextTicks (internal/process/task_queues.js:62:5)
   at processImmediate (internal/timers.js:434:9)
(node:22972) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:22972) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Looking at the code, I can imagine this problem zu occur, when `_options` is undefined [here](https://github.com/Niek/playwright-addons/blob/c1698c9dbe67708e8b0dcec5a800b53a592e742f/stealth/index.js#L23). I will gladly open a PR  to check `_options` for undefined and only then continue with the next two lines, but I am not sure if that is a sensible solution or if there is something entirely else wrong if `_options` is undefined?

**Comment by Niek** [comment]
With the beta release of [playwright-extra](https://github.com/berstend/puppeteer-extra/pull/303#issuecomment-775277480), this repo has become obsolete. I'm closing this issue and will be marking this repo as read-only.
